name: WindowsTest

on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        arch: [native]
        py: [cp39]
    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11


    - run: ${{ env.FC }} --version
      env:
        FC: ${{ steps.setup-fortran.outputs.fc }}    


    - run: python -m pip install --upgrade pip
    - name: Installing impy
      run: |
        $env:CMAKE_GENERATOR
        $env:FC
        python -m pip install --prefer-binary -v .[test]
      env: 
        CMAKE_GENERATOR: "MinGW Makefiles"
        FC: ${{ steps.setup-fortran.outputs.fc }}
    - run: python -m pytest -vv