name: Test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          ## TODO cannot test on windows for now, fortran compiler is not found
          # - os: windows-latest
          #   python-version: "3.10"

          - os: macos-latest
            python-version: "3.7"

          # version number must be string, otherwise 3.10 becomes 3.1
          - os: ubuntu-latest
            python-version: "3.9"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: generate key for caching from lfs files
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > lfs-assets-id
    - name: restore lfs cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('lfs-assets-id') }}-v1
    - name: pull lfs files
      run: git lfs pull
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11
    - run: python -m pip install --upgrade pip
    - run: python -m pip install --prefer-binary -v .[test]
    - run: python -m pytest tests/test_new_interface.py -vv
