name: Test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # version number must be string, otherwise 3.10 becomes 3.1
          - os: windows-latest
            python-version: "3.10"
          - os: macos-latest
            python-version: "3.7"
          - os: linux-latest
            python-version: "3.8"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11
    - run: python -m pip install --upgrade pip wheel
    # TODO no-build-isolation is required for now, needs to be fixed in CMakeLists.txt
    - run: python -m pip install --prefer-binary --no-build-isolation -v -e .[test]
    - run: python -m pytest
