name: Test

on:
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'README.*'

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          ## TODO cannot test on windows for now, fortran compiler is not found
          # - os: windows-latest
          #   python-version: "3.10"

          - os: macos-latest
            python-version: "3.7"

          # version number must be string, otherwise 3.10 becomes 3.1
          - os: linux-18.04
            python-version: "3.10"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: awvwgk/setup-fortran@main
      id: setup-fortran
      with:
        compiler: gcc
        version: 11
    - run: python -m pip install --upgrade pip wheel
    - run: python -m pip install --prefer-binary -v .[test]
    - run: python -m pytest tests/test_new_interface.py
